[unix_http_server]
file=/tmp/supervisor.sock   ; the path to the socket file
chmod=0700                  ; socket file mode (default 0700)
chown=nobody:nogroup        ; socket file uid:gid owner

[supervisord]
logfile=/tmp/supervisord.log ; main log file; default $CWD/supervisord.log
nodaemon=false               ; start in foreground if true; default false
silent=false                 ; no logs to stdout if true; default false
umask=022                    ; process file creation umask; default 022
user=supervisord            ; setuid to this UNIX account at startup; recommended if root
;directory=/tmp              ; default is not to cd during start
;environment=KEY="value"     ; key value pairs to add to environment
