[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
chown=invaliduser:invalidgroup

[supervisord]
logfile=/tmp/supervisord.log
nodaemon=false
silent=false
umask=022
user=thisuserdoesnotexist
directory=/path/that/does/not/exist
environment=KEY="value"
pidfile=/tmp/supervisord.pid
minfds=1024
minprocs=200
