[unix_http_server]
file=/tmp/taskmasterd.sock
chmod=0660
chown=root:taskmaster

[taskmasterd]
logfile=/var/log/
nodaemon=true
silent=false
umask=022
user=root
directory=/tmp
environment=KEY="value",DEBUG="1"
pidfile=/tmp/taskmasterd.pid
minfds=1024
minprocs=200

[include]
files=/etc/taskmaster/conf.d/*.conf
