[unix_http_server]
file=/tmp/taskmaster.sock
chmod=0700
chown=root:root

[supervisord]
logfile=/tmp/taskmasterd.log
nodaemon=false
silent=false
umask=022
user=root
directory=/tmp
environment=KEY="value",DEBUG="1"
pidfile=/tmp/taskmasterd.pid
minfds=1024
minprocs=200

[include]
files=/tmp/confs/conf.d/*.conf
