[test]
cmd = ./crash_program1.sh
numprocs = 2
umask = 022
workingdir = /Users/robingeral/Desktop/projets42/taskmaster/services/
autostart = true
autorestart = unexpected
exitcodes = 1 2
startretries = 1
starttime = 5
stopsignal = TERM
stoptime = 10
stdout = /dev/stdout
stderr = /dev/stderr
env = STARTED_BY=taskmaster ANSWER=42
