[cat_service]
cmd=/bin/cat
numprocs=6
umask=022
workingdir=/tmp
autostart=true
autorestart=true
exitcodes=0,2
startretries=5
starttime=6
stopsignal=TERM
stoptime=110
stdout=/tmp/cat_stdout.log
stderr=/tmp/cat_stderr.log
env=STARTED_BY="taskmaster",ANSWER="4"

[sleep_test]
cmd=/bin/sleep 300
numprocs=3
umask=022
workingdir=/tmp
autostart=true
autorestart=false
exitcodes=0
startretries=1
starttime=0
stopsignal=TERM
stoptime=10
stdout=/tmp/sleep_test_stdout.log
stderr=/tmp/sleep_test_stderr.log
env=TEST="sleep_test"

[sleep_test2]
cmd=/bin/sleep 20
numprocs=5
umask=022
workingdir=/tmp
autostart=true
autorestart=false
exitcodes=0
startretries=1
starttime=0
stopsignal=TERM
stoptime=10
stdout=/tmp/sleep_test_stdout.log
stderr=/tmp/sleep_test_stderr.log
env=TEST="sleep_test"
