[test]
cmd=sleep 10
numprocs=3
umask=022
workingdir=/tmp
autostart=true
autorestart=unexpected
exitcodes=1,2
startretries=1
starttime=4
stopsignal=QUIT
stoptime=10
stdout=/dev/stdout
stderr=/dev/stderr
env=STARTED_BY="taskmaster",ANSWER="42"
